# Generated by Django 2.1.1 on 2018-09-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180904_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='historical_data',
            field=models.TextField(),
        ),
    ]
