# Generated by Django 2.1.1 on 2018-09-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180904_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profession',
            new_name='professions',
        ),
    ]
